### ISSUE TITLE
Seems to be closing future milestones that have no open issues

### ISSUE THREAD

**Issue by bernhold** [MrGossett/github-action-milestone-closer#3]
This action appears to be removing milestones with future due dates but having no open issues.  From the documentation, this was not be behavior I expected.  Is that what's intended?

Though it is not very meaningful, I did a test in this repo: 
https://github.com/bernhold/milestone-closer-test
where I created four milestones: one past due, the others in the future, and associated issues with milestones 1, 2, and 4 with no issues on milestone 3.  Running github-action-milestone-closer resulted in milestone 3 being closed.

**Comment by bernhold** [comment]
Apologies.  I realized that I was using v1 instead of v1.1.  Once I updated, it looks like this is now working as expected.

**Comment by MrGossett** [comment]
@bernhold thanks for reaching out, and sorry I didn't see this sooner. Glad to hear it's working as expected.
